### ISSUE TITLE
Vagrant Box Too Small

### ISSUE THREAD

**Issue by elmerfud** [Tokutek/vagrant-tokutek-builder#1]
The vagrant box is too small to build tokumx as listed in the /etc/motd file.  

This instructions indicate.

To build a TokuMX release, please make sure each repository (ft-index,
mongo, and backup-community) has the right branch or tag checked out.  For
example, to build the head of the 1.1 branch, you can do this:

 $ (cd ft-index; git checkout releases/tokumx-1.1)
 $ (cd backup-community; git checkout releases/tokumx-1.1)
 $ (cd mongo; git checkout releases/tokumx-1.1)

Then, just run './build-tokumx.sh'.  It'll build everything with the right
optimizations.

The result of doing this is. 

objcopy:build/linux2/cc_gcc-4.7/cxx_g++-4.7/release/mongo/stripped/styCg2ky[.debug_info]: No space left on device
objcopy:build/linux2/cc_gcc-4.7/cxx_g++-4.7/release/mongo/stripped/styCg2ky: No
space left on device
scons: **\* [build/linux2/cc_gcc-4.7/cxx_g++-4.7/release/mongo/stripped/mongofiles.dbg] Error 1
scons: building terminated because of errors.

vagrant@quantal64:~$ df -h
Filesystem                  Size  Used Avail Use% Mounted on
/dev/mapper/quantal64-root  9.1G  8.5G   84M 100% /

The base box should be large enough to accommodate building the software according to the instructions.

**Comment by leifwalsh** [comment]
Yeah, this is annoying. If you can find another public 64-bit quantal box with a bigger disk, that should work. I have been able to build it successfully, though space is tight. Have you tried not building everything? Try starting fresh and running `scons --distname=1.2.1_elmerfud tokumx-1.2.1_elmerfud-linux-x86_64.tgz` instead of `scons dist`. That will avoid building the debuginfo tarball, which takes a lot of space.

**Comment by elmerfud** [comment]
Thank you, I was able to get it to build successfully using those options.

**Comment by robertjpayne** [comment]
This can still happen -- I found it easiest and in some ways faster to simply fire up a quantal instance on Digital Ocean and use the provision.sh manually commenting out the vagrant user stuff and it worked perfect.

**Comment by leifwalsh** [comment]
That's a good workaround, thanks.
