### ISSUE TITLE
Ubuntu repository set to Belgium

### ISSUE THREAD

**Issue by phils** [Tokutek/vagrant-tokutek-builder#2]
When I create the VM using the vagrant script, Ubuntu is setup to download updates from be.archive.ubuntu.com which is the Belgium mirror address.

Obviously it still works, but it's a long way to Belgium from Australia on the internet and it's quite slow!

Not sure if the image determines that on first boot, or if it's hardcoded into the image that is used.

**Comment by leifwalsh** [comment]
I am not a sophisticated vagrant user so I found an Ubuntu box that works ok and changed as little as possible. I'm also unsophisticated with Ubuntu. Is it enough to change "be" to "us" in sources.list at the beginning of the script? I can write the sed for this if that will work. 

—

**Comment by leifwalsh** [comment]
Or maybe if you're in Australia you should fork this repo and change it for yourself instead of letting me change it to the us. 

—

**Comment by phils** [comment]
Yes changing "be." to "us." should be enough.  Perhaps include the sed line if you're willing, and comment it so that users can edit it to whatever country they wish easily.  US would be a much better default than Belgium though.

**Comment by leifwalsh** [comment]
Ok sound good. Thanks. 

—

**Comment by leifwalsh** [comment]
@phils can you try it now?  You should be able to change the COUNTRY variable to whatever you want in provision.sh now.

**Comment by phils** [comment]
That works perfectly.  I set it to au and just provisioned a new box nicely, thanks!

**Comment by leifwalsh** [comment]
excellent, thanks for the report
