### ISSUE TITLE
Running out of space on box image

### ISSUE THREAD

**Issue by sepulworld** [Tokutek/vagrant-tokutek-builder#4]
Hi,

I am running into an issue when building using --ssl

the box runs out of space.  Can you please extend the size of the disk on the box?

vagrant@quantal64:~$ df -h
Filesystem                  Size  Used Avail Use% Mounted on
/dev/mapper/quantal64-root  9.1G  8.5G  124M  99% /
udev                        993M   12K  993M   1% /dev
tmpfs                       401M  272K  401M   1% /run
none                        5.0M     0  5.0M   0% /run/lock
none                       1002M     0 1002M   0% /run/shm
none                        100M     0  100M   0% /run/user
/dev/sda1                   228M   29M  188M  14% /boot
/vagrant                    465G  299G  167G  65% /vagrant

---snip---
objcopy --only-keep-debug build/linux2/cc_gcc-4.7/cxx_g++-4.7/release/ssl/mongo/stripped/mongo2toku.dbg
objcopy:build/linux2/cc_gcc-4.7/cxx_g++-4.7/release/ssl/mongo/stripped/stMVGs0P[.debug_info]: No space left on device
objcopy:build/linux2/cc_gcc-4.7/cxx_g++-4.7/release/ssl/mongo/stripped/stMVGs0P: No space left on device
scons: **\* [build/linux2/cc_gcc-4.7/cxx_g++-4.7/release/ssl/mongo/stripped/mongo2toku.dbg] Error 1
scons: building terminated because of errors.
---snip---

**Comment by leifwalsh** [comment]
I can't adjust the size of the base box but if you replace the configured base box with a different quantal image that has more space, you should be fine.

**Comment by sepulworld** [comment]
Thanks Leif.  I will give that a shot.

**Comment by sepulworld** [comment]
The build and make process should probably run from /vagrant  and not /home/vagrant, since the later is on the smaller root partition.  Basically, I will stick with the same box but reconfigure things a bit to have the builds run on the /vagrant mount.  I'll fork the project and try some things out. :)

**Comment by graingert** [comment]
Is this fixed by #5 ?

**Comment by sepulworld** [comment]
Yes
